language: node_js
node_js:
  - node
services:
  - mongodb
addons:
  apt:
    packages:
    - libgconf-2-4
    - libcurl3
cache:
  yarn: true
install:
- yarn install --ignore-engines
before_script:
  - sleep 15
  - mongo test --eval 'db.createUser({ user:"travis", pwd:"test", roles:["readWrite"] });'
script:
- yarn lint
- yarn test:unit
- yarn test:func
deploy:
  provider: heroku
  api_key:
    secure: A+QwObKI5CX7mUjxBQAvfSPb4Z8WZzqiRICmh1W3o4suGoYnr3j87IyCqRvPESJ+KxCCte6R4LuZSs2Xo9OySQSNxnwslNDsTC+AdR1Ner40qlP0pHQb+1IfjEb81xBDK6yVOAmP9rcpOGc98HztXVK9/4vMN1Rz7lNmcVw1SEdA6+cwra+zk4yibQYaMOn9HmxmfPBmOHElPemGUSTdCDROLo2Zd+XjtKVcedyLQGSDNeniHzcf2ZU/NGsxIPF+civbYrmfWzzQsWFVlt5JnoVgYlnnDi+fsd7Y2tl5fxm3I8g8Ng4G/ZPPGYcrMOmh4LtDFRUH+yQPVHheDNk11eHsRgQTd4e9S3l+LoGZmZCiFwcpO0T+wRgL7bT7UwGVpIxxa9k8ohCvVzDfvTJ0MfgayaQH0rSztVhLGT5B+jnoLYN/mz+WXueSQWnqETOgEkqwknXQvKWaUz1RsfMnUOCJnp9KITQQJ9BwLMjbO5EvFDrurAZIlAJ06pEuZdSwVVUMYJgs1v6FS+vjPXPhc8WImEpQ98ViZJffh1x7jxrULquq5NQV/zIkwfKWpKg0eNzoARVr+RQC4z35ZmpQP1GJGMAVBt+2i5FxQuUMIZE6R3Z8NkGkx43pGpKfIR0A6xP6PLJAlYIF2P4Z/6UEjsa2S5b76tNqZfLVOBztR3E=
  app: $APP
  on:
    branch: main
